print('welcome to the python survey!!!')
n = input('what is your name?')
a = input('how old are you?')
dob = input('when were you born?')
e = input('what is your email?')
def c():
    print('calculating...')
c()
c()
c()
print('success!!!')
print(f'thank you, {n}! we will send you the results at {e}. have a nice day!')
